name: build
on: [push]
defaults:
  run:
    shell: bash
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: src/package-lock.json
      - run: npm install
      - run: npm run build